# Generated by Django 4.2.1 on 2023-06-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rental_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrate',
            name='daily_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='real_cost',
            field=models.FloatField(),
        ),
    ]
