# Generated by Django 4.2.1 on 2023-06-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_category_country_director_film_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='available_in_countries',
            field=models.ManyToManyField(related_name='country_available', to='films.country'),
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(to='films.category'),
        ),
        migrations.AddField(
            model_name='film',
            name='created_in_country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='country_created', to='films.country'),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(to='films.director'),
        ),
    ]
