# Generated by Django 4.2.1 on 2023-06-04 16:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_film_available_in_countries_film_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_date', models.DateField(default=datetime.date.today)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_name', to='films.film')),
            ],
        ),
    ]
