# Generated by Django 4.2.1 on 2023-05-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_date_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_completion',
        ),
    ]
