# Generated by Django 4.2.1 on 2023-06-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(blank=True, choices=[('sunny', 'sunny'), ('cloudy', 'cloudy'), ('windy', 'windy'), ('rainy', 'rainy'), ('stormy', 'stormy')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
