# Generated by Django 4.2.1 on 2023-05-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.family'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.FloatField(),
        ),
    ]
