# Generated by Django 4.2.1 on 2023-05-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_animal_family_alter_animal_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='family',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
