# Generated by Django 4.2.1 on 2023-06-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        ('accounts', '0002_userprofile_favorite_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_film',
            field=models.ManyToManyField(blank=True, related_name='users_favorite', to='films.film'),
        ),
    ]
